version: 2.5.0.{build}
image: Visual Studio 2017
install:
- cinst gtksharp -y
- appveyor DownloadFile "https://dot.net/v1/dotnet-install.ps1"
- ps: "& ./dotnet-install.ps1 -Version 3.0.100-preview5-011568"
build_script:
- set BASE=%APPVEYOR_BUILD_FOLDER%
- set BUILD_VERSION_NUMBER=000%APPVEYOR_BUILD_NUMBER%
- set BUILD_VERSION=2.5.0-build%BUILD_VERSION_NUMBER:~-4%
- msbuild -t:Package -p:BuildVersion=%BUILD_VERSION% build\Build.proj /v:minimal /logger:"C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll" /consoleloggerparameters:NoSummary /bl:MSBuild.BuildPackage.binlog
- msbuild -t:BuildAddins build\Build.proj /v:minimal /logger:"C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll" /consoleloggerparameters:NoSummary /bl:MSBuild.BuildAddins.binlog
on_failure:
- ps: Get-ChildItem -File MSBuild.*.binlog | % { Push-AppveyorArtifact $_ -DeploymentName MSBuild-Binlog }
test: off
#test_script:
#- nunit-console --framework=4.5 --include=TestPlatform artifacts/Release/net45/test/Eto.Test.dll
artifacts:
- path: artifacts/nuget/Release/*.nupkg
  name: nuget
- path: artifacts/samples
  name: samples
  type: zip
- path: artifacts/test
  name: test
  type: zip
- path: artifacts/addin/Release/VisualStudio/Eto.Addin.VisualStudio.vsix
  name: vsix
branches:
  only:
  - develop
  - master
skip_branch_with_pr: true
deploy:
- provider: Environment
  name: MyGet
  on:
    branch: develop
